---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: spells.magic.mayday
spec:
  group: magic.mayday
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                incantation:
                  type: string
                powerLevel:
                  type: integer
  scope: Namespaced
  names:
    plural: spells
    singular: spell
    kind: Spell
